#pragma once

#define BG_BUFFER_SIZE 128
#define SM_BUFFER_SIZE 32

#define KV_PARSER_TYPE_DELIMITER ":"
#define KV_PARSER_KEY_DELIMITER "="
#define KV_PARSER_VALUE_DELIMITER "\n"

#define KV_STORAGE_STRUCTURE_LIST "L"
#define KV_STORAGE_STRUCTURE_HASH "H"

#define KV_STORAGE_HASH_SIZE 32

#define KV_CLI_MAX_OPEN_DATABASES 256

#define KV_STORAGE_STRUCTURE KV_STORAGE_STRUCTURE_LIST
