name: C/C++ CI

on:
  push:
    branches: [ "main" ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          mkdir -p ./build
          cd ./build
          cmake ..
          make
      - name: Test
        run: |
          cd ./build
          ctest -V --output-on-failure
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen
      - name: Run Doxygen
        working-directory: ${{ github.workspace }}
        run: doxygen Doxyfile
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/html
